spring:
  application:
    name: csx
server:
  port: 9092
eureka:
  instance:
    hostname: node2
  client:
    service-url:
      defaultZone: http://node1:9091/rg/,http://node3:9093/rg/
    fetch-registry: true
    register-with-eureka: true